services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./todo:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"